### PR TITLE
Feature/unique identifiers for colors

### PR DESCRIPTION
**Pull request by bytesandroses**
**Summary**
An input element has been added so that users can manually enter a hex code, which automatically updates the color palette selection. This means that the hex code is now displayed in two places: first inside the hexCode div, and again inside the input element. Do you think we should modify the code so that it's only shown in the input element?

_HTML Changes:_
1. Added input element for hex codes

_JavaScript Changes:_
1. Modified the color palette event handler so that the hex code input element updates with new color selections
2. Added a hex code event handler so that color palette selection can updates with manual hex code input

### CODE REVIEW

**Review by EslamAbdElhakem — APPROVED** [review]
Great work on this PR, [bytesandroses]! 🎉

I've reviewed the changes, and everything looks good to me. This PR is now approved and ready to be merged.

Best,
[EslamAbdElhakem]

**Review by EslamAbdElhakem — APPROVED** [review]

**Review by Lithakazi101 — APPROVED** [review]
Looks good to me.

**Review by Lithakazi101 — APPROVED** [review]
Looks good to me.

**Review by Lithakazi101 — APPROVED** [review]
looks good to me.

**Review by Lithakazi101 — APPROVED** [review]

**Review by Lithakazi101 — APPROVED** [review]

**Pull request merged**
